# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56266d90e01454f08689f1501fb26937c9414477dcf2cf99faa45a00e65fe330d055d561cedee9a1f18a25dad279b569c9d75cb6c9e00f91a19e467024cd01e

test:
  secret_key_base: 6f7df0f12a30c44824994c770e256d490aac20c18ed51fef7f6bd390718904e452072d0cdd1dc1ef51f891465703c5a9f2a549f6c0d30e50624d02906377212d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
